# SPDX-FileCopyrightText: 2026 Joe Heffer
#
# SPDX-License-Identifier: MIT

# Wokwi simulator project. Build first with `esphome compile dimpsy.yaml`.
# https://docs.wokwi.com/wokwi-ci/getting-started
[wokwi]
version = 1
firmware = ".esphome/build/dimpsy/.pioenvs/dimpsy/firmware.factory.bin"
elf = ".esphome/build/dimpsy/.pioenvs/dimpsy/firmware.elf"
